#item-service-dev.yml
spring:
 application:
  name: item-service
 cloud:
  config:
   override-none: true
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
   username: root
   password: root   
server:
  port: 8001
  
eureka:
  client:
    service-url:
     defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
 

 
